#!/bin/bash

echo "=============================================="
echo "  DEMO STUDENT MANAGEMENT SYSTEM"
echo "=============================================="
echo ""
echo "Chương trình đã được biên dịch thành công!"
echo ""
echo "Các file đã tạo:"
echo "  ✓ Student.java (66 dòng)"
echo "  ✓ StudentManagement.java (319 dòng)"
echo "  ✓ Tổng: 385 dòng code"
echo ""
echo "=============================================="
echo "  CHỨC NĂNG CHÍNH"
echo "=============================================="
echo ""
echo "1. ĐĂNG KÝ HỌC PHẦN"
echo "   - Nhập thông tin sinh viên"
echo "   - Tối thiểu 10 sinh viên"
echo "   - 3 khóa học: Java, .Net, C/C++"
echo "   - Validation: Không trùng khóa học trong cùng kỳ"
echo ""
echo "2. TÌM KIẾM VÀ SẮP XẾP"
echo "   - Tìm theo tên (hỗ trợ tìm một phần)"
echo "   - Tự động sắp xếp theo tên"
echo "   - Sử dụng Collections.sort() + Comparator"
echo ""
echo "3. CẬP NHẬT/XÓA"
echo "   - Tìm theo mã sinh viên"
echo "   - Chọn Update (U) hoặc Delete (D)"
echo "   - Cập nhật: Tên, Học kỳ, Khóa học"
echo ""
echo "4. BÁO CÁO"
echo "   - Tổng hợp theo sinh viên"
echo "   - Hiển thị: Mã | Tên | Khóa học | Tổng số"
echo "   - Sử dụng HashMap và HashSet"
echo ""
echo "=============================================="
echo "  DỮ LIỆU MẪU ĐỂ TEST"
echo "=============================================="
echo ""
echo "Sinh viên 1:  FX00001 | Nguyen Van A   | Fall2022   | Java"
echo "Sinh viên 2:  FX00002 | Nguyen Van B   | Fall2022   | .Net"
echo "Sinh viên 3:  FX00003 | Nguyen Van C   | Spring2023 | Java"
echo "Sinh viên 4:  FX00001 | Nguyen Van A   | Spring2023 | Java (OK-khác kỳ)"
echo "Sinh viên 5:  FX00004 | Tran Thi D     | Fall2022   | C/C++"
echo "Sinh viên 6:  FX00005 | Le Van E       | Summer2023 | Java"
echo "Sinh viên 7:  FX00006 | Pham Thi F     | Fall2022   | .Net"
echo "Sinh viên 8:  FX00007 | Hoang Van G    | Spring2023 | C/C++"
echo "Sinh viên 9:  FX00008 | Vo Thi H       | Fall2022   | Java"
echo "Sinh viên 10: FX00009 | Dang Van I     | Summer2023 | .Net"
echo ""
echo "=============================================="
echo ""
echo "Bạn muốn chạy chương trình ngay bây giờ?"
echo "  [1] Có, chạy ngay"
echo "  [2] Không, xem hướng dẫn trước"
echo ""
read -p "Nhập lựa chọn (1/2): " choice

if [ "$choice" = "1" ]; then
    echo ""
    echo "Đang khởi động chương trình..."
    echo ""
    sleep 1
    java -cp bin com.learn.StudentManagement
else
    echo ""
    echo "Hướng dẫn chi tiết: cat demo-instructions.md"
    echo "Để chạy sau: ./run-student-management.sh"
    echo "Hoặc: java -cp bin com.learn.StudentManagement"
    echo ""
fi
